spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/pcparts}
    username: ${SPRING_DATASOURCE_USERNAME:pcparts}
    password: ${SPRING_DATASOURCE_PASSWORD:pcparts}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      validation-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: validate   # prod: validate (oder 'none'); nimm 'update' nur, wenn du's wirklich willst
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

  # In Prod KEIN H2
  h2:
    console:
      enabled: false

logging:
  level:
    org.hibernate.SQL: warn
    org.atmosphere: warn

# Optional: wenn du Actuator nutzt, Health für Readiness
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
